##IMPORTING LIBRARIES

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

##MNIST is a standardized, handwritten dataset in which data about a particular image is present
##Grayscale values range from 0 to 255, for a 28x28 pixel

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape) #60000 input vectors
print(y_train.shape, y_train)
print(x_test.shape)
print(y_test.shape)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
(60000, 28, 28)
(60000,) [5 0 4 ... 5 6 8]
(10000, 28, 28)
(10000,)


##DEFINING THE VARIABLES AND RESHAPING THE VECTOR

In [ ]:
x_train, x_test = x_train / 255.0, x_test / 255.0 # dividing all the inuts by 255 to get values between 0 and 1 for easier classification
x_train = x_train.reshape((x_train.shape[0], 28 * 28)) #making all the input data points into the same dimension
x_test = x_test.reshape((x_test.shape[0], 28 * 28))
y_train = to_categorical(y_train, 10)  # performs one hot encoding on training set
y_test = to_categorical(y_test, 10)  # performs one hot encoding on test set
#One hot encoding converts all the decimal values in the training and test set into 0s and 1s for easier computation of data


In [ ]:
print(y_test)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


##MODEL TRAINING AND COMPILATION

In [ ]:
model = models.Sequential([
    layers.Dense(128, activation='relu', input_shape=(28*28,)), #ReLU= max(0,z) where z is a given linear function .
    #input dimension of 28x28=784(pixel data) hidden layer
    layers.Dropout(0.2),
    layers.Dense(10, activation='softmax')]) #softmax is used to convert vector into a distribution function (output layer)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy', #categorical loss entropy is used as a loss function
              metrics=['accuracy'])

##MODEL FITTING

In [ ]:
model.fit(x_train, y_train, epochs=5, batch_size=64) #epoch is one whole cycle through the training set

Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8394 - loss: 0.5632
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9483 - loss: 0.1757
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9635 - loss: 0.1264
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9714 - loss: 0.0981
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9743 - loss: 0.0849


#MODEL ACCURACY

In [ ]:
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_acc}") # accuracy of classifying the mnsit data into categories from 0 to 9 for 28x28 grayscale images



313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9734 - loss: 0.0863
Test accuracy: 0.9772999882698059
